title: Xudong Zhu
# tagline: Here is personal website of Xudong Zhu. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Xudong holds a Master of Arts (MA) in American Studies from Ruprecht-Karls-Universität Heidelberg. 
#Comment out url when working locally to resolve base urls correctly
url: 

# Owner/author information
owner:
  name: Xudong Zhu
  avatar: 1.png
  # bio: Xudong holds a Master of Arts (MA) in American Studies from Ruprecht-Karls-Universität Heidelberg.
  email: xudong.zhu01@gmail.com
  cv: https://x-zhu01.github.io/documents/cv xudong zhu.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: lancecai2002
  #github: GuangLun2000
  linkedin: xudong-zhu-457bb3220
  #scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  #researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: CV
    url: /cv/
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: Thesises
    url: /thesises/
  - title: Blogs
    url: /blogs/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Berlin
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/12/27 by Xudong Zhu.
